### ISSUE TITLE
[BUG] Script doesn't work until I manually restart it

### ISSUE THREAD

**Issue by Kurosar** [WolfKnight98/wk_wars2x#22] opened 2021-08-18 09:10 UTC
**Describe the bug**
The script is ensured in server.cfg and I can see the "splashscreen" in the server console when the server starts.
However, the script is not responding to the /radar_remote command or the keybind.
To make it work, I have to type "restart wk_wars2x" in the console, and after that everything is working fine.

**To Reproduce**
Download the script on a fresh server install (build 2372) and try using it.
Note : I'm using QBCore Framework, but it shouldn't interfere since the script is standalone.

**Expected behaviour**
The script should work on server start without the need of typing "restart wk_wars2x" in the server console.

**Desktop (please complete the following information):**
Server Build used "Tuner DLC with +set sv_enforceGameBuild 2372"
Client Build used "Canary 4382"
Radar version : Latest from git clone

**Comment by WolfKnight98** [comment] 2021-08-18 09:22
Hi Kurosar, can you provide me with a screenshot of your console when you spawn in.

**Comment by Kurosar** [comment] 2021-08-18 09:53
![image](https://user-images.githubusercontent.com/4887819/129877909-ee28d777-b599-4bce-a888-76654c1860fe.png)
That's basically it, no errors clientside or serverside.

Note : The server is running on linux, and the script works fine on server start when the server was on version 2189

**Comment by Kurosar** [comment] 2021-08-18 09:54
After I type restart wk_wars2x
![image](https://user-images.githubusercontent.com/4887819/129878184-feaea4dd-3499-43f9-8927-3805e8a325b8.png)

**Comment by WolfKnight98** [comment] 2021-08-18 12:44
It appears that you are experiencing the same issue as those in a very minute group. Presently, the cause is entirely unknown to me, which means I cannot fix it. We thought it might have been something to do with the playerSpawned event not being triggered, but we're not sure.

**Comment by Kurosar** [comment] 2021-08-18 17:52
I haven't, however i could try it on a dev server maybe.
This is super strange, are the other people mentioning the issue running on the tuner dlc server build too ?

**Comment by WolfKnight98** [comment] 2021-08-18 18:16
> 
> 
> I haven't, however i could try it on a dev server maybe.
> This is super strange, are the other people mentioning the issue running on the tuner dlc server build too ?

I'm not sure, if you add me on Discord (WolfKnight#8586) I'll add you to a group chat with a few others who're having the same issue.

**Comment by Kurosar** [comment] 2021-08-19 17:59
Added and willing to help do some tests :p

**Comment by Log-nx** [comment] 2021-08-28 16:24
> > I haven't, however i could try it on a dev server maybe.
> > This is super strange, are the other people mentioning the issue running on the tuner dlc server build too ?
> 
> I'm not sure, if you add me on Discord (WolfKnight#8586) I'll add you to a group chat with a few others who're having the same issue.


I have send you a request on discord as well, it seems I am apart of this issue using the latest 4394 build / tuner dlc / Qbus

**Comment by WolfKnight98** [comment] 2021-08-30 19:36
The issue should be fixed with version 1.3.1

**Closed** 2021-08-31 15:36 UTC
Labels: bug

**Comment by Xorbite** [comment] 2022-07-10 23:48
I am currently experiencing the same issue and I have the latest version of the script
